--------------------------------------------------------
--  Arquivo criado - quinta-feira-maio-15-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CULTURA
--------------------------------------------------------

  CREATE TABLE "RM563928"."CULTURA" 
   (	"ID_CULTURA" NUMBER(*,0), 
	"NOME_CULTURA" VARCHAR2(255 BYTE), 
	"OBSERVACAO_CULTURA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM563928.CULTURA
SET DEFINE OFF;
Insert into RM563928.CULTURA (ID_CULTURA,NOME_CULTURA,OBSERVACAO_CULTURA) values ('1','Cana-de-açúcar',null);
--------------------------------------------------------
--  DDL for Index CULTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM563928"."CULTURA_PK" ON "RM563928"."CULTURA" ("ID_CULTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table CULTURA
--------------------------------------------------------

  ALTER TABLE "RM563928"."CULTURA" ADD CONSTRAINT "CULTURA_PK" PRIMARY KEY ("ID_CULTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM563928"."CULTURA" MODIFY ("ID_CULTURA" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."CULTURA" MODIFY ("NOME_CULTURA" NOT NULL ENABLE);
