--------------------------------------------------------
--  Arquivo criado - quinta-feira-maio-15-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IRRIGACAO
--------------------------------------------------------

  CREATE TABLE "RM563928"."IRRIGACAO" 
   (	"ID_IRRIGACAO" NUMBER(*,0), 
	"QUANTIDADE_TOTAL" FLOAT(126), 
	"DATA_HORA" DATE, 
	"OBSERVACAO" VARCHAR2(255 BYTE), 
	"SENSOR_ID_SENSOR" NUMBER(*,0), 
	"CULTURA_ID_CULTURA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;

   COMMENT ON COLUMN "RM563928"."IRRIGACAO"."QUANTIDADE_TOTAL" IS 'Quantidade de irrigação aplicada';
   COMMENT ON COLUMN "RM563928"."IRRIGACAO"."DATA_HORA" IS 'Data e hora do inicio da irrigação';
   COMMENT ON COLUMN "RM563928"."IRRIGACAO"."OBSERVACAO" IS 'Observações sobre a irrigação';
REM INSERTING into RM563928.IRRIGACAO
SET DEFINE OFF;
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('1','15,5',to_date('14/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('2','10',to_date('14/05/25','DD/MM/RR'),'pH fora da faixa ideal','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('3','12,3',to_date('14/05/25','DD/MM/RR'),'Baixa umidade do solo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('4','9',to_date('02/05/25','DD/MM/RR'),'Falta de potássio detectada','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('5','10,8',to_date('02/05/25','DD/MM/RR'),'Baixa umidade do solo','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('6','15,4',to_date('02/05/25','DD/MM/RR'),'Verificação automática agendada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('7','12,2',to_date('02/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('8','9,7',to_date('03/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('9','12,4',to_date('03/05/25','DD/MM/RR'),'Baixa umidade do solo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('10','8,7',to_date('03/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('11','14,9',to_date('03/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('12','16',to_date('04/05/25','DD/MM/RR'),'Baixa umidade do solo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('13','11,9',to_date('04/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('14','10,4',to_date('04/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('15','12,2',to_date('04/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('16','13,2',to_date('05/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('17','9,6',to_date('05/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('18','15,1',to_date('05/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('19','12,4',to_date('05/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('20','8,2',to_date('06/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('21','9,6',to_date('06/05/25','DD/MM/RR'),'Umidade crítica registrada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('22','10,7',to_date('06/05/25','DD/MM/RR'),'Verificação automática agendada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('23','11,2',to_date('06/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('24','9,6',to_date('07/05/25','DD/MM/RR'),'Baixa umidade do solo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('25','12,3',to_date('07/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('26','12,6',to_date('07/05/25','DD/MM/RR'),'Umidade crítica registrada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('27','8,8',to_date('07/05/25','DD/MM/RR'),'Umidade crítica registrada','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('28','15,6',to_date('08/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('29','11,4',to_date('08/05/25','DD/MM/RR'),'pH fora da faixa ideal','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('30','8,1',to_date('08/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('31','14,2',to_date('08/05/25','DD/MM/RR'),'pH fora da faixa ideal','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('32','13,8',to_date('09/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('33','11,6',to_date('09/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('34','14,2',to_date('09/05/25','DD/MM/RR'),'Baixa umidade do solo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('35','15,1',to_date('09/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('36','15,6',to_date('10/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('37','13',to_date('10/05/25','DD/MM/RR'),'Baixa umidade do solo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('38','11,5',to_date('10/05/25','DD/MM/RR'),'Verificação automática agendada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('39','9,1',to_date('10/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('40','12,6',to_date('11/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('41','10',to_date('11/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('42','12,2',to_date('11/05/25','DD/MM/RR'),'Verificação automática agendada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('43','12,8',to_date('11/05/25','DD/MM/RR'),'pH fora da faixa ideal','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('44','9,1',to_date('12/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('45','8,5',to_date('12/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('46','12,8',to_date('12/05/25','DD/MM/RR'),'pH fora da faixa ideal','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('47','15,5',to_date('12/05/25','DD/MM/RR'),'Baixa umidade do solo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('48','12,4',to_date('13/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('49','8',to_date('13/05/25','DD/MM/RR'),'Verificação automática agendada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('50','10,7',to_date('13/05/25','DD/MM/RR'),'Falta de potássio detectada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('51','13,1',to_date('13/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('52','10,2',to_date('14/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('53','8,3',to_date('14/05/25','DD/MM/RR'),'Verificação automática agendada','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('54','9,9',to_date('14/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('55','9,7',to_date('14/05/25','DD/MM/RR'),'Baixa umidade do solo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('56','15,3',to_date('15/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('57','13,5',to_date('15/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('58','14,3',to_date('15/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('59','13,6',to_date('15/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('60','12,8',to_date('16/05/25','DD/MM/RR'),'Verificação automática agendada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('61','11,1',to_date('16/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('62','11,4',to_date('16/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('63','15,9',to_date('16/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('64','14,9',to_date('17/05/25','DD/MM/RR'),'Falta de potássio detectada','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('65','8,7',to_date('17/05/25','DD/MM/RR'),'pH fora da faixa ideal','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('66','15,6',to_date('17/05/25','DD/MM/RR'),'Verificação automática agendada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('67','12,7',to_date('17/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('68','11,2',to_date('18/05/25','DD/MM/RR'),'Verificação automática agendada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('69','15,2',to_date('18/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('70','14,1',to_date('18/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('71','11,5',to_date('18/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('72','14,6',to_date('19/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('73','10,1',to_date('19/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('74','15,9',to_date('19/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('75','13,1',to_date('19/05/25','DD/MM/RR'),'Falta de potássio detectada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('76','12,5',to_date('20/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('77','15,9',to_date('20/05/25','DD/MM/RR'),'Falta de potássio detectada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('78','15,6',to_date('20/05/25','DD/MM/RR'),'pH fora da faixa ideal','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('79','10,8',to_date('20/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('80','11,7',to_date('21/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('81','12,6',to_date('21/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('82','11,5',to_date('21/05/25','DD/MM/RR'),'Falta de potássio detectada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('83','9,7',to_date('21/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('84','9,8',to_date('22/05/25','DD/MM/RR'),'Falta de potássio detectada','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('85','13,7',to_date('22/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('86','10,6',to_date('22/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('87','10,8',to_date('22/05/25','DD/MM/RR'),'Umidade crítica registrada','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('88','9,1',to_date('23/05/25','DD/MM/RR'),'Verificação automática agendada','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('89','11,3',to_date('23/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('90','15,3',to_date('23/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('91','15,2',to_date('23/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('92','9,6',to_date('24/05/25','DD/MM/RR'),'Baixa umidade do solo','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('93','13,8',to_date('24/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('94','9,4',to_date('24/05/25','DD/MM/RR'),'Irrigação preventiva baseada em previsão','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('95','14',to_date('24/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('96','9,8',to_date('25/05/25','DD/MM/RR'),'Verificação automática agendada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('97','15',to_date('25/05/25','DD/MM/RR'),'Ativada automaticamente por falta de nutrientes','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('98','13,4',to_date('25/05/25','DD/MM/RR'),'pH fora da faixa ideal','3','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('99','13,5',to_date('25/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','2','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('100','15,8',to_date('26/05/25','DD/MM/RR'),'Irrigação manual por observação de campo','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('101','9,1',to_date('26/05/25','DD/MM/RR'),'Fósforo abaixo do esperado','1','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('102','14,2',to_date('26/05/25','DD/MM/RR'),'Umidade crítica registrada','4','1');
Insert into RM563928.IRRIGACAO (ID_IRRIGACAO,QUANTIDADE_TOTAL,DATA_HORA,OBSERVACAO,SENSOR_ID_SENSOR,CULTURA_ID_CULTURA) values ('103','9,9',to_date('26/05/25','DD/MM/RR'),'Sistema ativado por múltiplas condições críticas','4','1');
--------------------------------------------------------
--  DDL for Index IRRIGACAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM563928"."IRRIGACAO_PK" ON "RM563928"."IRRIGACAO" ("ID_IRRIGACAO", "CULTURA_ID_CULTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table IRRIGACAO
--------------------------------------------------------

  ALTER TABLE "RM563928"."IRRIGACAO" ADD CONSTRAINT "IRRIGACAO_PK" PRIMARY KEY ("ID_IRRIGACAO", "CULTURA_ID_CULTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM563928"."IRRIGACAO" MODIFY ("ID_IRRIGACAO" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."IRRIGACAO" MODIFY ("QUANTIDADE_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."IRRIGACAO" MODIFY ("DATA_HORA" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."IRRIGACAO" MODIFY ("SENSOR_ID_SENSOR" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."IRRIGACAO" MODIFY ("CULTURA_ID_CULTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table IRRIGACAO
--------------------------------------------------------

  ALTER TABLE "RM563928"."IRRIGACAO" ADD CONSTRAINT "IRRIGACAO_CULTURA_FK" FOREIGN KEY ("CULTURA_ID_CULTURA")
	  REFERENCES "RM563928"."CULTURA" ("ID_CULTURA") ENABLE;
  ALTER TABLE "RM563928"."IRRIGACAO" ADD CONSTRAINT "IRRIGACAO_SENSOR_FK" FOREIGN KEY ("SENSOR_ID_SENSOR")
	  REFERENCES "RM563928"."SENSOR" ("ID_SENSOR") ENABLE;
