--------------------------------------------------------
--  Arquivo criado - quinta-feira-maio-15-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SENSOR
--------------------------------------------------------

  CREATE TABLE "RM563928"."SENSOR" 
   (	"ID_SENSOR" NUMBER(*,0), 
	"NOME_SENSOR" VARCHAR2(255 BYTE), 
	"DESCRICAO" VARCHAR2(255 BYTE), 
	"DATA_INSTALACAO" DATE, 
	"LATITUDE" FLOAT(126), 
	"LONGITUDE" FLOAT(126), 
	"TIPO_SENSOR_ID_TIPO_SENSOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM563928.SENSOR
SET DEFINE OFF;
Insert into RM563928.SENSOR (ID_SENSOR,NOME_SENSOR,DESCRICAO,DATA_INSTALACAO,LATITUDE,LONGITUDE,TIPO_SENSOR_ID_TIPO_SENSOR) values ('1','Sensor de Fósforo (Botão Azul)','Detecta presença/ausência de fósforo',to_date('14/05/25','DD/MM/RR'),'-23,5505','-46,6333','1');
Insert into RM563928.SENSOR (ID_SENSOR,NOME_SENSOR,DESCRICAO,DATA_INSTALACAO,LATITUDE,LONGITUDE,TIPO_SENSOR_ID_TIPO_SENSOR) values ('2','Sensor de Potássio (Botão Amarelo)','Detecta presença/ausência de potássio',to_date('14/05/25','DD/MM/RR'),'-23,5505','-46,6333','1');
Insert into RM563928.SENSOR (ID_SENSOR,NOME_SENSOR,DESCRICAO,DATA_INSTALACAO,LATITUDE,LONGITUDE,TIPO_SENSOR_ID_TIPO_SENSOR) values ('3','Sensor de pH (LDR)','Simula leitura de pH com base em luminosidade',to_date('14/05/25','DD/MM/RR'),'-23,5505','-46,6333','1');
Insert into RM563928.SENSOR (ID_SENSOR,NOME_SENSOR,DESCRICAO,DATA_INSTALACAO,LATITUDE,LONGITUDE,TIPO_SENSOR_ID_TIPO_SENSOR) values ('4','Sensor de Umidade (DHT22)','Mede a umidade do solo',to_date('14/05/25','DD/MM/RR'),'-23,5505','-46,6333','1');
--------------------------------------------------------
--  DDL for Index SENSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM563928"."SENSOR_PK" ON "RM563928"."SENSOR" ("ID_SENSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table SENSOR
--------------------------------------------------------

  ALTER TABLE "RM563928"."SENSOR" ADD CONSTRAINT "SENSOR_PK" PRIMARY KEY ("ID_SENSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM563928"."SENSOR" MODIFY ("ID_SENSOR" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."SENSOR" MODIFY ("NOME_SENSOR" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."SENSOR" MODIFY ("TIPO_SENSOR_ID_TIPO_SENSOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SENSOR
--------------------------------------------------------

  ALTER TABLE "RM563928"."SENSOR" ADD CONSTRAINT "SENSOR_TIPO_SENSOR_FK" FOREIGN KEY ("TIPO_SENSOR_ID_TIPO_SENSOR")
	  REFERENCES "RM563928"."TIPO_SENSOR" ("ID_TIPO_SENSOR") ENABLE;
