--------------------------------------------------------
--  Arquivo criado - quinta-feira-maio-15-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPO_SENSOR
--------------------------------------------------------

  CREATE TABLE "RM563928"."TIPO_SENSOR" 
   (	"ID_TIPO_SENSOR" NUMBER(*,0), 
	"NOME_SENSOR" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM563928.TIPO_SENSOR
SET DEFINE OFF;
Insert into RM563928.TIPO_SENSOR (ID_TIPO_SENSOR,NOME_SENSOR) values ('1','ESP32');
--------------------------------------------------------
--  DDL for Index TIPO_SENSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM563928"."TIPO_SENSOR_PK" ON "RM563928"."TIPO_SENSOR" ("ID_TIPO_SENSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table TIPO_SENSOR
--------------------------------------------------------

  ALTER TABLE "RM563928"."TIPO_SENSOR" MODIFY ("ID_TIPO_SENSOR" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."TIPO_SENSOR" MODIFY ("NOME_SENSOR" NOT NULL ENABLE);
  ALTER TABLE "RM563928"."TIPO_SENSOR" ADD CONSTRAINT "TIPO_SENSOR_PK" PRIMARY KEY ("ID_TIPO_SENSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
